language: node_js
node_js:
  - 0.10
env:
  - SLIMERJSLAUNCHER=$(which firefox) DISPLAY=:99.0 PATH=$TRAVIS_BUILD_DIR/slimerjs:$PATH
addons:
  firefox: "25.0"
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "wget http://download.slimerjs.org/v0.9/0.9.0/slimerjs-0.9.0.zip"
  - "unzip slimerjs-0.9.0.zip"
  - "mv slimerjs-0.9.0 ./slimerjs"
deploy:
  provider: npm
  email: christoph.burgmer@gmail.com
  api_key:
    secure: EsvyCKvVOxMZDU5yvIGiwpqWTGlHUWZtcFLTaXqdJB4PseJQpDoWohFL+aH/N3cc5DgxwtCTRunwQ1jesGsQb++AWMZ5TeWuYDQXvvU6vs5oGY7wChqb70Ksjbcyp4MIzyUEotfwt+PGlDKPEOb/S3wnBBRjF9m5fWfnS4RjVZQ=
  on:
    tags: true
    repo: cburgmer/rasterizeHTML.js
branches:
  only:
    - master
